firstsite/AnnounceSystem/urls.py
from django.urls import path
from . import views

app_name = 'AnnounceSystem'

urlpatterns = [
    path('', views.index, name='index'),
    path('index/', views.index, name='index'),
    path('index/<str:pageindex>/', views.index, name='index'),
    path('error/<int:status>/', views.test_error, name='test'),
    path('detail/<int:detailid>/', views.detail, name='detail'),
    path('login/<str:loc>/', views.login, name='login'),
    path('login/', views.login, name='login'),
    path('adminshow/', views.adminShow, name='showData'),
    path('adminshow/<str:pageindex>/', views.adminShow, name='showData'),
    path('addnews/', views.newsadd, name='newsadd'),
    path('editnews/', views.newsedit, name='newsedit'),
    path('editnews/<int:newsid>', views.newsedit, name='newsedit'),
    path('editnews/<int:newsid>/<str:edittype>', views.newsedit, name='newsedit'),
    path('delnews/', views.newsdelete, name='newsdelete'),
    path('delnews/<int:newsid>', views.newsdelete, name='newsdelete'),
    path('delnews/<int:newsid>/<str:deletetype>', views.newsdelete, name='newsdelete'),
]

firstsite/firstsite/urls.py
from xml.etree.ElementInclude import include
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),  # Including another URLconf
    path('AnnounceSystem/', include('AnnounceSystem.urls')),
    path('snippets/', include('snippets.urls')),
]

firstsite/polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'

urlpatterns = [
    # path('', views.index, name='index'),
    path('', views.IndexView.as_view(), name='index'),
    path('offical/', views.officaltutor, name='tutor'),
    path('error/', views.test_error, name='error'),
    # path('<int:question_id>/', views.detail, name= 'detail'),  # <int:> only accept type:int. ex: /polls/5/
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    # path('<int:question_id>/results/', views.results, name='results'),  # ex: /polls/5/results/
    path('<int:pk>/results', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),  # ex: /polls/5/vote/  
    path('contact/', views.contact, name='contact'),
    path('contact/success', views.contact_success, name='contact_success'),
]

firstsite/AnnounceSystem/models.py
from django.db import models

# Create your models here.

class NewsUnit(models.Model):
    catego = models.CharField(max_length=10, null=False)
    nickname = models.CharField(max_length=20, null=False)
    title = models.CharField(max_length=50, null=False)
    message = models.TextField(null=False)
    pubtime = models.DateTimeField(auto_now=True)
    enabled = models.BooleanField(default=False)
    press = models.IntegerField(default=0)
    
    def __str__(self):
        return self.title

firstsite/AnnounceSystem/views.py
from django.shortcuts import render, redirect
from django.http import Http404, HttpResponse
from django.urls import reverse
from django.contrib import auth
from django.contrib.auth import authenticate
from .models import NewsUnit


import math
# Create your views here.

# def index(request):
    # return HttpResponse('<h1> this is AnnSystem </h1>')

def test_error(request, status=None):
    status = 404
    return HttpResponse(status=status)

#def index(request):
#    context = {'message' : "hello"}
#    return render(request, 'AnnounceSystem/index.html', context)

page1 = 1  #目前頁面

def index(request, pageindex=None):
    global page1  #重複開啟本網頁時需保留 page1 的值
    pagesize = 4  #每頁顯示的資料筆數
    newsall = NewsUnit.objects.all().order_by('-id')  #讀取新聞資料表,依時間遞減排序
    # NewsUnit.objects.all()[:5] 取出前五筆 or 排序 NewsUnit.objects.all().order_by('-id')[:5]
    # NewsUnit.objects.filter().count() -> int
    datasize = len(newsall)  #新聞筆數
    totpage = math.ceil(datasize / pagesize)  #總頁數
    if pageindex==None:  #無參數
        page1 = 1
        newsunits = NewsUnit.objects.filter(enabled=False).order_by('-id')[:pagesize]
    elif pageindex=='1':  #上一頁
        start = (page1-2)*pagesize  #該頁第1筆資料
        if start >= 0:  #有前頁資料就顯示
            # newsunits = NewsUnit.objects.filter(enabled=True).order_by('-id')[start:(start+pagesize)]
            newsunits = NewsUnit.objects.filter(enabled=False).order_by('-id')[start:(start+pagesize)]
            page1 -= 1
    elif pageindex=='2':  #下一頁
        start = page1*pagesize  #該頁第1筆資料
        if start < datasize:  #有下頁資料就顯示
            # newsunits = NewsUnit.objects.filter(enabled=True).order_by('-id')[start:(start+pagesize)]
            newsunits = NewsUnit.objects.filter(enabled=False).order_by('-id')[start:(start+pagesize)]
            page1 += 1
    elif pageindex=='3':  #由詳細頁面返回首頁
        start = (page1-1)*pagesize  #取得原有頁面第1筆資料
        # newsunits = NewsUnit.objects.filter(enabled=True).order_by('-id')[start:(start+pagesize)]
        newsunits = NewsUnit.objects.filter(enabled=False).order_by('-id')[start:(start+pagesize)]

    currentpage = page1  #將目頁前頁面以區域變數傳回html
    return render(request, "AnnounceSystem/index.html", locals())

def detail(request, detailid=None):
	unit = NewsUnit.objects.get(id=detailid)
	category = unit.catego
	title = unit.title
	pubtime = unit.pubtime
	nickname = unit.nickname
	message = unit.message
	unit.press += 1
	unit.save()
	
	return render(request, "AnnounceSystem/detail.html", locals())

def login(request, loc=None):
    title = "Login System"
    message = ""
    if loc == "guest":
        message = "請進行登入"
        return render(request, "AnnounceSystem/login.html", locals())
    
    if request.method == 'POST' and loc == "admin":
        name = request.POST['username'].strip()
        password = request.POST['password']
        admin01 = authenticate(username=name, password=password)
        if admin01 is not None:
            if admin01.is_active:
                auth.login(request, admin01)
                message = "login success" + " loc = " +loc
                # return render(request, "AnnounceSystem/announadmin.html", locals())
                return redirect('AnnounceSystem:showData')
            else:
                message = "Invalid account."
            
        else:
            message = " Lonin not pass. "
            return render(request, "AnnounceSystem/login.html", locals())

    return render(request, "AnnounceSystem/login.html", locals())
    # return render(request, reverse('AnnounceSystem/login.html'), locals())
    # return redirect('AnnounceSystem:index')

def adminShow(request, pageindex=None):
    global page1  
    pagesize = 4 
    newsall = NewsUnit.objects.all().order_by('-id')
    datasize = len(newsall) 
    totpage = math.ceil(datasize / pagesize)
    if pageindex==None:
        page1 = 1
        newsunits = NewsUnit.objects.order_by('-id')[:pagesize]
    elif pageindex=='1': 
        start = (page1-2)*pagesize 
        if start >= 0:  
            newsunits = NewsUnit.objects.order_by('-id')[start:(start+pagesize)]
            page1 -= 1
    elif pageindex=='2':  
        start = page1*pagesize  
        if start < datasize:  
            newsunits = NewsUnit.objects.order_by('-id')[start:(start+pagesize)]
            page1 += 1
    elif pageindex=='3':  
        start = (page1-1)*pagesize  
        newsunits = NewsUnit.objects.order_by('-id')[start:(start+pagesize)]
    currentpage = page1  
    return render(request, "AnnounceSystem/announadmin.html", locals())

def newsadd(request):
    message = ""
    category = request.POST.get('news_type', '')
    subject = request.POST.get('news_subject', '')
    editor = request.POST.get('news_editor', '')
    content = request.POST.get('news_content', '')
    ok = request.POST.get('news_ok', '')

    if subject == '' or editor == '' or content == '':
        message = "Can not be blank."
    else:
        if ok == "yes":
            enabled = True
        else:
            enabled = False
        unit = NewsUnit.objects.create(catego=category, nickname=editor, title=subject, message=content, enabled=enabled, press=0)
        unit.save()
        return redirect('AnnounceSystem:showData')
    return render(request, "AnnounceSystem/newsadd.html", locals())

def newsedit(request, newsid=None, edittype=None):
	unit = NewsUnit.objects.get(id=newsid)
	categories = ["公告", "更新", "活動", "新書", "其他"]
	if edittype == None:
		type = unit.catego
		subject = unit.title
		editor = unit.nickname
		content = unit.message
		ok = unit.enabled
	elif edittype == '1':
		category = request.POST.get('news_type', '')
		subject = request.POST.get('news_subject', '')
		editor = request.POST.get('news_editor', '')
		content = request.POST.get('news_content', '')
		ok = request.POST.get('news_ok', '')
		if ok=='yes':
			enabled = True
		else:
			enabled = False
		unit.catego=category
		unit.nickname=editor
		unit.title=subject
		unit.message=content
		unit.enabled=enabled
		unit.save()
		return redirect('AnnounceSystem:showData')
	return render(request, "AnnounceSystem/newsedit.html", locals())

def newsdelete(request, newsid=None, deletetype=None):
	unit = NewsUnit.objects.get(id=newsid)
	if deletetype == None:
		type = str(unit.catego.strip())
		subject = unit.title
		editor = unit.nickname
		content = unit.message
		date = unit.pubtime
	elif deletetype == '1':
		unit.delete()
		return redirect('AnnounceSystem:showData')
	return render(request, "AnnounceSystem/newsdelete.html", locals())

firstsite/AnnounceSystem/templates/AnnounceSystem/announadmin.html
{% extends 'AnnounceSystem/base.html' %}
{% block content %}
<div class="contentbox">
    <table width="100%">
        <tr>
            <a href="{% url 'AnnounceSystem:newsadd' %}" title="新聞編輯">新增公告</a>
            <th align="left">分類</th>
            <th align="left">標題</th>
            <th align="left">時間</th>
            <th align="left">編輯</th>
        </tr>
        {% for unit in newsunits %}
            <tr class="alt">
            <td><div class="typeblock">【{{ unit.catego }}】</div></td>
            <td><a href="{% url 'AnnounceSystem:newsedit' unit.id %}">{{ unit.title }}</a></td>
            <td>{{ unit.pubtime }}</td>
            <td>
                {% comment %} <a href="/newsedit/{{unit.id}}/" title="新聞編輯"> <img src="{% static "images/note_edit.png" %}"  width="16" height="16" /></a> {% endcomment %}
                <a href="{% url 'AnnounceSystem:newsedit' unit.id %}" title="新聞編輯">編輯</a>
                {% comment %} <a href="/newsdelete/{{unit.id}}/" title="新聞刪除"><img src="{% static "images/cross.png" %}" width="16" height="16" /></a> {% endcomment %}
                <a href="{% url 'AnnounceSystem:newsdelete' unit.id %}" title="新聞刪除">刪除</a>
            </td>
            </tr>
        {% empty %}
            <div class="status warning">
                <p><span>注意</span> 目前新聞資料庫中沒有任何資料！</p>
            </div>
        {% endfor %}
    </table>
    <br>
    <div class="topfunction">
    {% if currentpage > 1 %}
        <a href="{% url 'AnnounceSystem:showData' pageindex=1 %}" title="上一頁">上一頁</a>
    {% endif %}
    {% if currentpage < totpage %}
        <a href="{% url 'AnnounceSystem:showData' pageindex=2 %}" title="下一頁">下一頁</a>
    {% endif %}
    </div>
</div>
{% endblock content %}

firstsite/AnnounceSystem/templates/AnnounceSystem/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet">
  <link href="https://getbootstrap.com/docs/5.3/assets/css/docs.css" rel="stylesheet">
  {% load static %}
  <title>Announce</title>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"></script>
</head>
<body>

<div class="container">
  <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
    <div class="col-md-3 mb-2 mb-md-0">
      <a href="/" class="d-inline-flex link-body-emphasis text-decoration-none">
        <svg class="bi" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"/></svg>
      </a>
    </div>

    <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
      <li><a href="#" class="nav-link px-2 link-secondary">Home</a></li>
      <li><a href="#" class="nav-link px-2">Features</a></li>
      <li><a href="#" class="nav-link px-2">Pricing</a></li>
      <li><a href="#" class="nav-link px-2">FAQs</a></li>
      <li><a href="{% url 'polls:index' %}" class="nav-link px-2">Polls</a></li>
    </ul>

    <div class="col-md-3 text-end">
      <form>
        <button type="submit" class="btn btn-outline-primary me-2" formaction="{% url 'AnnounceSystem:login' loc="guest" %}">Login</button>
        {% comment %} <button type="submit" class="btn btn-outline-primary me-2" formaction="{% url 'AnnounceSystem:login'%}">Login</button> {% endcomment %}
        {% comment %} {% url 'login' as the_url %} {% endcomment %}
        {% comment %} <button type="submit" class="btn btn-outline-primary me-2" formaction="{{the_url}}">Login</button> {% endcomment %}
        <button type="submit" class="btn btn-outline-primary me-2" formaction="{% url 'AnnounceSystem:test' status=404 %}">Click me</button>
        <button type="button" class="btn btn-primary">Sign-up</button>
      </form>
    </div>
  </header>
</div>

<div class="container">
  {% block content %}
  {% endblock content %}
</div>

  <div class="b-example-divider"></div>


  <div class="container">
    <footer class="py-5">
      <div class="row">
        <div class="col-6 col-md-2 mb-3">
          <h5>Section</h5>
          <ul class="nav flex-column">
            <li class="nav-item mb-2"><a href="{% url 'AnnounceSystem:index' %}" class="nav-link p-0 text-body-secondary">Home</a></li>
            <li class="nav-item mb-2"><a href="{% url 'polls:contact' %}" class="nav-link p-0 text-body-secondary">Contact</a></li>
            <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Pricing</a></li>
            <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">FAQs</a></li>
            <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">About</a></li>
          </ul>
        </div>
  
        <div class="col-6 col-md-2 mb-3">
          <h5>Section</h5>
          <ul class="nav flex-column">
            <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Home</a></li>
            <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Features</a></li>
            <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Pricing</a></li>
            <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">FAQs</a></li>
            <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">About</a></li>
          </ul>
        </div>
  
        <div class="col-6 col-md-2 mb-3">
          <h5>Section</h5>
          <ul class="nav flex-column">
            <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Home</a></li>
            <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Features</a></li>
            <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Pricing</a></li>
            <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">FAQs</a></li>
            <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">About</a></li>
          </ul>
        </div>
  
        <div class="col-md-5 offset-md-1 mb-3">
          <form>
            <h5>Subscribe to our newsletter</h5>
            <p>Monthly digest of what's new and exciting from us.</p>
            <div class="d-flex flex-column flex-sm-row w-100 gap-2">
              <label for="newsletter1" class="visually-hidden">Email address</label>
              <input id="newsletter1" type="text" class="form-control" placeholder="Email address">
              <button class="btn btn-primary" type="button">Subscribe</button>
            </div>
          </form>
        </div>
      </div>
  
      <div class="d-flex flex-column flex-sm-row justify-content-between py-4 my-4 border-top">
        <p>&copy; 2023 Company, Inc. All rights reserved.</p>
        <ul class="list-unstyled d-flex">
          <li class="ms-3"><a class="link-body-emphasis" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#twitter"/></svg></a></li>
          <li class="ms-3"><a class="link-body-emphasis" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#instagram"/></svg></a></li>
          <li class="ms-3"><a class="link-body-emphasis" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#facebook"/></svg></a></li>
        </ul>
      </div>
    </footer>
  </div>
</body>
</html>

firstsite/AnnounceSystem/templates/AnnounceSystem/detail.html
{% extends 'AnnounceSystem/base.html' %}
{% load static %} 
{% block content %}
    <div class="contentbox">
        <table width="100%">
        <tr>
            <th align="center"><span class="typeblock">【 {{category}} 】&nbsp;&nbsp;</span>&nbsp;&nbsp;標題 : {{title}}</th>
        </tr>
        <tr>
            <td>
                <span class="newsinfo" >
                    <div align="center" style="border:1px solid red">
                    <img src="{% static "images/date.png" %}" alt="" width="16" height="16" />&nbsp;DATE : {{pubtime}}&nbsp;
                    <img src="{% static "images/user.png" %}" alt="" width="16" height="16" />&nbsp;USER : {{nickname}}
                    </div>
                    <p>&nbsp;&nbsp;{{message}}</p>
                </span>
            </td>
        </tr>
        </table>
    </div>

    <div class="topfunction">
        <a href="{% url 'AnnounceSystem:index' pageindex="3" %}" title="返回首頁">
            <img src="{% static "images/home.png" %}" alt="返回首頁" width="86" height="32" /></a>
        </div>
    </div>
{% endblock %}

firstsite/AnnounceSystem/templates/AnnounceSystem/index.html
{% extends 'AnnounceSystem/base.html' %}
{% load static %}
{% block content %}
<h1>{{message}}</h1><br>
{{request.get_full_path}}<br>
<p>Show four item = {{newsunits}} </p><br><br><br>
<div class="contentbox">
    <table width="100%">
    <tr>
        <th align="left">分類</th>
        <th align="left">標題</th>
        <th align="left">時間</th>
        <th align="left">點閱數</th>
    </tr>

    {% for unit in newsunits %}
    {% comment %} 將資料庫依照分類、標題、上傳時間、點閱數用迴圈顯示在表格上 {% endcomment %}
        <tr class="alt">
            <td><div class="typeblock">【{{ unit.catego }}】</div></td>
            {% comment %} <td><a href="/detail/{{unit.id}}/">{{ unit.title }}</a></td>  {% endcomment %}
            <td><a href="{% url 'AnnounceSystem:detail' unit.id %}">{{ unit.title }}</a></td>
            {% comment  %}點標題傳送連結到指定網址 {% endcomment %}
            <td>{{ unit.pubtime }}</td>
            <td>{{ unit.press }}</td>
        </tr>
    {% empty %}
        {% comment %} 當迴圈為空值時 {% endcomment %}
        <div class="status warning">
            <p><span>注意 !</span> 目前新聞資料庫中沒有任何資料！</p>
        </div>
    {% endfor %}
    </table>
    <br>
    <div class="topfunction">
        {% comment %} 換頁功能 {% endcomment %}
        {% if currentpage > 1 %}
            <a href="{% url 'AnnounceSystem:index' pageindex="1" %}" title="上一頁">上一頁</a>
        {% endif %}
        {% if currentpage < totpage %}
            <a href="{% url 'AnnounceSystem:index' pageindex=2 %} " title="下一頁">下一頁</a>
        {% endif %}
    </div>
</div>
{% endblock content %}

firstsite/AnnounceSystem/templates/AnnounceSystem/login.html
{% extends 'AnnounceSystem/base.html' %}
{% load static %} 
{% block content %}
<div id="login">
    <h3 class="text-center text-white pt-5">Login form</h3>
    <div class="container">
        <div id="login-row" class="row justify-content-center align-items-center">
            <div id="login-column" class="col-md-6">
                <div class="login-box col-md-12">
                    <form id="login-form" class="form" action="{% url 'AnnounceSystem:login' loc="admin" %}" method="post">
                        {% csrf_token %}
                        <h3 class="text-center text-info">{{title}} : {{message}}</h3>
                        <div class="form-group">
                            <label for="username" class="text-info">Username:</label><br>
                            <input type="text" name="username" id="username" class="form-control">
                        </div>
                        <div class="form-group">
                            <label for="password" class="text-info">Password:</label><br>
                            <input type="password" name="password" id="password" class="form-control">
                        </div>
                        <div class="form-group">
                            <label for="remember-me" class="text-info"><span>Remember me</span> <span><input id="remember-me" name="remember-me" type="checkbox"></span></label><br>
                            <input type="submit" name="submit" class="btn btn-info btn-md" value="submit">
                        </div>
                        <div id="register-link" class="text-right">
                            <a href="{% url 'AnnounceSystem:login' loc="user" %}" class="text-info">Register here</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

firstsite/AnnounceSystem/templates/AnnounceSystem/newsadd.html
{% extends 'AnnounceSystem/base.html' %}
{% block content %}
    <div>
        <form action="." id="form1" name="form1" method="POST">
            {% csrf_token %}
            <table align="center">
                <tr>
                    <th align="left"> 新增新聞</th>
                </tr>
                <tr>
                    <td valign="baseline"><strong>分類</strong></td>
                    <td valign="baseline">
                        <select name="news_type" id="news_type">
                            <option value="公告" selected="selected">公告</option>
                            <option value="更新">更新</option>
                            <option value="活動">活動</option>
                            <option value="新書">新書</option>
                            <option value="其他">其他</option>
                        </select>
                    </td>
                </tr>
                <tr>
                    <td valign="baseline"><strong>標題</strong></td>
                    <td valign="baseline"><input type="text" name="news_subject" id="news_subject" size="40" required></td>
                </tr>
                <tr>
                    <td valign="baseline"><strong>編輯者</strong></td>
                    <td valign="baseline"><input type="text" name="news_editor" id="news_editor" required></td>
                </tr>
                <tr>
                    <td valign="baseline"><strong>內容</strong></td>
                    <td valign="baseline"><textarea name="news_content" id="news_content" cols="60" rows="15" required></textarea></td>
                </tr>
                <tr>
                    <td valign="baseline"><strong>審核內容</strong></td>
                    <td valign="baseline">
                        <input type="radio" name="news_ok" id="news_ok2" value="yes" checked="checked">已通過
                        <input type="radio" name="news_ok" id="news_ok" value="no">審核中
                    </td>
                </tr>
                <tr>
                    <td>&nbsp;</td>
                    <td>
                        <input type="submit" name="button" id="button" value="送出" />
                        <input type="reset" name="button2" id="button2" value="重設" />
                        {% comment %} <input type="button" name="button3" id="button3" value="回主頁面" onclick="history.back()"> {% endcomment %}
                        <input type="button" name="button3" id="button3" value="回主頁面" onclick="location.href='{% url 'AnnounceSystem:showData' %}'">
                    </td>
                </tr>                
            </table>
            <span style="color:red">{{message}}</span>  
        </form>
    </div>
{% endblock content %}

firstsite/AnnounceSystem/templates/AnnounceSystem/newsdelete.html
{% extends "AnnounceSystem/base.html" %}
{% load static %} 

{% block content %}
    <div class="contentbox">
        <form action="{% url 'AnnounceSystem:newsdelete' newsid=newsid deletetype=1 %}" id="form1" name="form1" method="POST">
            {% csrf_token %}
            <table align="center">
                <tr>
                    <th colspan="2" align="left"> 刪除新聞</th>
                </tr>
                <tr>
                    <td><strong>分類</strong></td>
                    <td>{{type}}</td>
                </tr>
                <tr>
                    <td><strong>標題</strong></td>
                    <td>{{subject}}</td>
                </tr>
                <tr>
                    <td><strong>編輯者</strong></td>
                    <td>{{editor}}</td>
                </tr>
                <tr>
                    <td><strong>內容</strong></td>
                    <td>{{content}}</td>
                </tr>
                <tr>
                    <td><strong>日期</strong></td>
                    <td>{{date}}</td>
                </tr>
                <tr>
                    <td><strong><font color="#FF0000">是否確定刪除？</font></strong></td>
                    <td><input type="submit" name="button" id="button" value="確定" />
                    <input type="button" name="button3" id="button3" value="回主頁面" onclick="location.href='{% url 'AnnounceSystem:showData' %}'" />
                </tr>
            </table>
            <span style="color:red">{{message}}</span>
        </form>
    </div>
{% endblock %}

firstsite/AnnounceSystem/templates/AnnounceSystem/newsedit.html
{% extends "AnnounceSystem/base.html" %}
{% load static %} 

{% block content %}
    <div class="contentbox">
        <form action="{% url 'AnnounceSystem:newsedit' newsid=newsid edittype=1 %}" id="form1" name="form1" method="POST">
            {% csrf_token %}
            <table align="center">
                <tr>
                    <th colspan="2" align="left"> 編輯新聞</th>
                </tr>
                <tr>
                    <td valign="baseline"><strong>分類</strong></td>
                    <td valign="baseline">
                        <select name="news_type" id="news_type">
                            {% for category in categories %}
                            {% if type == category %}
                                <option value={{category}} selected="selected">{{category}}</option>
                            {% else %}
                                <option value={{category}}>{{category}}</option>
                            {% endif %}
                            {% endfor %}
                        </select>
                    </td>
                </tr>
                <tr>
                    <td valign="baseline"><strong>標題</strong></td>
                    <td valign="baseline"><input name="news_subject" type="text" id="news_subject" size="45" value="{{subject}}" /></td>
                </tr>
                <tr>
                    <td valign="baseline"><strong>編輯者</strong></td>
                    <td valign="baseline"><input type="text" name="news_editor" id="news_editor" value="{{editor}}" /></td>
                </tr>
                <tr>
                    <td valign="baseline"><strong>內容</strong></td>
                    <td valign="baseline"><textarea name="news_content" id="news_content" cols="60" rows="15">{{content}}</textarea></td>
                </tr>
                <tr>
                    <td valign="baseline"><strong>審核</strong></td>
                    <td valign="baseline">
                        {% if ok %}
                        <input type="radio" name="news_ok" id="news_ok2" value="yes" checked="checked" />已通過
                        <input name="news_ok" type="radio" id="news_ok" value="no" />審核中
                        {% else %}
                        <input type="radio" name="news_ok" id="news_ok2" value="yes" />已通過
                        <input name="news_ok" type="radio" id="news_ok" value="no" checked="checked" />審核中
                        {% endif %}
                    </td>
                </tr>
                <tr>
                    <td>&nbsp;</td>
                    <td><input type="submit" name="button" id="button" value="送出" />
                        <input type="button" name="button3" id="button3" value="回主頁面" onclick="location.href='{% url 'AnnounceSystem:showData' %}'" /></td>
                </tr>
            </table>
            <span style="color:red">{{message}}</span>
        </form>
    </div>
{% endblock %}